# Generated by Django 5.0.2 on 2024-03-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actividad_Fisica',
            new_name='Actividad',
        ),
    ]
